language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t rmill040/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rmill040/docker-react npm run test